# Generated by Django 4.2.13 on 2026-04-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('pace', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('low_confidence_reconstruction', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('team_id', models.IntegerField(null=True)),
                ('height_inches', models.IntegerField(null=True)),
                ('position', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PBPEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.IntegerField()),
                ('clock_seconds', models.IntegerField()),
                ('event_type', models.CharField(max_length=30)),
                ('event_msg_type', models.IntegerField()),
                ('team_id', models.IntegerField(null=True)),
                ('player_id', models.IntegerField(null=True)),
                ('points_scored', models.IntegerField(default=0)),
                ('score_home', models.IntegerField(null=True)),
                ('score_away', models.IntegerField(null=True)),
                ('score_margin', models.IntegerField(null=True)),
                ('home_lineup', models.JSONField(null=True)),
                ('away_lineup', models.JSONField(null=True)),
                ('opp_is_big_lineup', models.BooleanField(null=True)),
                ('opp_is_shooter_lineup', models.BooleanField(null=True)),
                ('opp_is_smallball', models.BooleanField(null=True)),
                ('is_clutch', models.BooleanField(null=True)),
                ('is_fast_game', models.BooleanField(null=True)),
                ('is_slow_game', models.BooleanField(null=True)),
                ('game', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='pbp_events',
                    to='ingestion.game',
                )),
            ],
            options={
                'db_table': 'pbp_events',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                )),
                ('season', models.CharField(max_length=10)),
                ('three_point_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('three_point_att', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='season_stats',
                    to='ingestion.player',
                )),
            ],
            options={
                'db_table': 'player_season_stats',
                'unique_together': {('player', 'season')},
            },
        ),
    ]
